# Default values for iis-static.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: microsoft/iis
  tag: windowsservercore-ltsc2016
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources:
  limits:
    memory: 1G 
    cpu: 1
  requests:
    cpu: 1

nodeSelector: {
  beta.kubernetes.io/os: windows
}

tolerations: 
  - key: "azure.com/aci"
    operator: "Exists"
    effect: "NoSchedule"


affinity: {}
